
services:
  music-separator:
    build: .
    ports:
      - "8000:8000"
    # Если нужен GPU:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]