services:
  music-separator:
    build: .
    ports:
      - "8000:8000"

    # === Блок для использования GPU NVIDIA ===
    # Если у вас есть дискретная видеокарта NVIDIA и вы выполнили установку
    # NVIDIA Container Toolkit (https://docs.nvidia.com/datacenter/cloud-native/),
    # раскомментируйте этот блок – модель будет работать на GPU, что даст
    # значительный прирост скорости инференса.
    # Если видеокарты нет или тулкит не установлен, просто закомментируйте
    # этот блок или удалите его – тогда всё работает на CPU.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]